sonar.projectKey=optimuswave14_bad-ml-code
sonar.organization=optimuswave14

# Project display name
sonar.projectName=bad-ml-code

# Version shown in dashboard
sonar.projectVersion=1.0

# Scan current folder
sonar.sources=.

# Encoding
sonar.sourceEncoding=UTF-8
